### ISSUE TITLE
Shall use this npm for my app?

### ISSUE THREAD

**Issue by Prabuganesan** [glynnbird/couchwarehouse#11]
I have used relational npm for create a doc in CouchDB. CouchDB have following data formate. 

```
{
  "_id": "pfm2653_2_0224E977-A319-6E19-A065-4EE1E3AABDE7",
  "_rev": "1-293de9bf186747f3b696d106650de688",
  "data": {
    "student_no": "1",
    "student_name": "Mohammed Safeer Zaheer",
    "type": "pfm2653"
  }
}

```

Shall I use this npm for moving this formate data into postgres?

**Comment by glynnbird** [comment]
couchwarehouse could certainly be used to move this data to Postgres.
