### ISSUE TITLE
Display couchwarehouse message properly for databaseType

### ISSUE THREAD

**Issue by yrimal** [glynnbird/couchwarehouse#16]
When running couchwarehouse for MySql or Postgresql, it still shows an information from sqlite3.

![image](https://user-images.githubusercontent.com/6102813/51906131-67f66b00-23eb-11e9-977f-bf379ec012dc.png)

Platform: Windows 10 64-bit
Postgresql Version: 11.1 
Couchdb : 2.3.1
Couchwarehouse:  1.4.0

**Comment by glynnbird** [comment]
Oh yes. I think that's just the message that is `console.log`'d out. It should vary according to which `databaseType` you choose. If you run `psql` you should find you have a table called `medic` with some data in. I'll use this issue to track the bug on the `console.log` message.

**Comment by yrimal** [comment]
Yes, just the log message. It was synced properly to postgres database. Looking at the code changes, closing it as resolved.
