### ISSUE TITLE
Couchwarehouse unable to migrate database from database with hyphen

### ISSUE THREAD

**Issue by yrimal** [glynnbird/couchwarehouse#20]
Couchwarehouse is not able to migrate database from couchdb to postgresql when the database name in couchdb contains hyphen. It'd be great if you cold fix it and be able to migrate database with hyphen. Otherwise, you can handle this condition. 

![image](https://user-images.githubusercontent.com/6102813/52039117-c5a9c500-255b-11e9-8eef-1030da66e663.png)

Platform: Windows 10 64-bit
Postgresql Version: 11.1
Couchdb : 2.3.1
Couchwarehouse: 1.4.0

**Comment by glynnbird** [comment]
This should be fixed in 1.5.0
